# [left, right, top, bottom]
WIDTH = 2.6
HEIGHT = 1.5
DISTANCE_BETWEEN_OBSTACLES = 0.3
OBSTACTLE_WIDTH = 0.02

obstacles = [
    [0, WIDTH, 0, OBSTACTLE_WIDTH],       # top border
    [0, WIDTH, HEIGHT-OBSTACTLE_WIDTH, HEIGHT],    # bottom border    
    [0, OBSTACTLE_WIDTH, 0, HEIGHT],        # left border
    [WIDTH-OBSTACTLE_WIDTH, WIDTH, 0, HEIGHT],   # right border

    [0, 
     WIDTH-DISTANCE_BETWEEN_OBSTACLES, 
     1 * DISTANCE_BETWEEN_OBSTACLES + OBSTACTLE_WIDTH, 
     1 * DISTANCE_BETWEEN_OBSTACLES + 2 * OBSTACTLE_WIDTH],

    [DISTANCE_BETWEEN_OBSTACLES, 
     WIDTH, 
     2 * DISTANCE_BETWEEN_OBSTACLES + OBSTACTLE_WIDTH, 
     2 * DISTANCE_BETWEEN_OBSTACLES + 2 * OBSTACTLE_WIDTH],

    [0, 
     WIDTH-DISTANCE_BETWEEN_OBSTACLES, 
     3 * DISTANCE_BETWEEN_OBSTACLES + OBSTACTLE_WIDTH, 
     3 * DISTANCE_BETWEEN_OBSTACLES + 2 * OBSTACTLE_WIDTH],

    [DISTANCE_BETWEEN_OBSTACLES, 
     WIDTH, 
     4 * DISTANCE_BETWEEN_OBSTACLES + OBSTACTLE_WIDTH, 
     4 * DISTANCE_BETWEEN_OBSTACLES + 2 * OBSTACTLE_WIDTH],
]